
package com.softlimits.clarinet;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMessageService", targetNamespace = "http://www.softlimits.com/Clarinet.Trade")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.softlimits.clarinet.ObjectFactory.class
})
public interface IMessageService {


    /**
     * 
     * @param message
     * @return
     *     returns com.softlimits.clarinet.ArrayOfMessageOutputData
     */
    @WebMethod(operationName = "ProcessMessage", action = "http://www.softlimits.com/Clarinet.Trade/IMessageService/ProcessMessage")
    @WebResult(name = "MessageDataList", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageDataList")
    public ArrayOfMessageOutputData processMessage(
        @WebParam(name = "Message", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "Message")
        byte[] message);

    /**
     * 
     * @param messageId
     * @return
     *     returns com.softlimits.clarinet.ArrayOfMessageOutputData
     */
    @WebMethod(operationName = "GetMessageResultData", action = "http://www.softlimits.com/Clarinet.Trade/IMessageService/GetMessageResultData")
    @WebResult(name = "MessageDataList", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageDataList")
    public ArrayOfMessageOutputData getMessageResultData(
        @WebParam(name = "MessageId", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageId")
        String messageId);

    /**
     * 
     * @param messageId
     * @return
     *     returns com.softlimits.clarinet.ArrayOfMessageOutputIdentification
     */
    @WebMethod(operationName = "GetQueuedMessageIds", action = "http://www.softlimits.com/Clarinet.Trade/IMessageService/GetQueuedMessageIds")
    @WebResult(name = "MessageIdList", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageIdList")
    public ArrayOfMessageOutputIdentification getQueuedMessageIds(
        @WebParam(name = "MessageId", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageId")
        String messageId);

    /**
     * 
     * @param messageId
     */
    @WebMethod(operationName = "ChangeQueuedToProcessed", action = "http://www.softlimits.com/Clarinet.Trade/IMessageService/ChangeQueuedToProcessed")
    @Oneway
    public void changeQueuedToProcessed(
        @WebParam(name = "MessageId", targetNamespace = "http://www.softlimits.com/Clarinet.Trade", partName = "MessageId")
        String messageId);

}
