
package ifthenpay.mbw;

import ifthenpay.mbw.abstracttypes.StringArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IfthenPayMBWHttpPost", targetNamespace = "https://www.ifthenpay.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ifthenpay.mbw.ObjectFactory.class,
    ifthenpay.mbw.abstracttypes.ObjectFactory.class,
    org.xmlsoap.schemas.soap.encoding.ObjectFactory.class
})
public interface IfthenPayMBWHttpPost {


    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.RespostaPedido
     */
    @WebMethod(operationName = "SetPedidoSync")
    @WebResult(name = "Body", partName = "Body")
    public RespostaPedido setPedidoSync(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "referencia", partName = "referencia")
        String referencia,
        @WebParam(name = "valor", partName = "valor")
        String valor,
        @WebParam(name = "nrtlm", partName = "nrtlm")
        String nrtlm,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "descricao", partName = "descricao")
        String descricao);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     */
    @WebMethod(operationName = "SetPedidoSyncJSON")
    public void setPedidoSyncJSON(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "referencia", partName = "referencia")
        String referencia,
        @WebParam(name = "valor", partName = "valor")
        String valor,
        @WebParam(name = "nrtlm", partName = "nrtlm")
        String nrtlm,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "descricao", partName = "descricao")
        String descricao);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     */
    @WebMethod(operationName = "EstadoPedidosSyncJSON")
    public void estadoPedidosSyncJSON(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "idspagamento", partName = "idspagamento")
        StringArray idspagamento);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     * @return
     *     returns https.www_ifthenpay.RespostaPedidoEstado
     */
    @WebMethod(operationName = "EstadoPedidos")
    @WebResult(name = "Body", partName = "Body")
    public RespostaPedidoEstado estadoPedidos(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "idspagamento", partName = "idspagamento")
        StringArray idspagamento);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     */
    @WebMethod(operationName = "EstadoPedidosJSON")
    public void estadoPedidosJSON(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "idspagamento", partName = "idspagamento")
        StringArray idspagamento);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.RespostaPedido
     */
    @WebMethod(operationName = "SetPedido")
    @WebResult(name = "Body", partName = "Body")
    public RespostaPedido setPedido(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "referencia", partName = "referencia")
        String referencia,
        @WebParam(name = "valor", partName = "valor")
        String valor,
        @WebParam(name = "nrtlm", partName = "nrtlm")
        String nrtlm,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "descricao", partName = "descricao")
        String descricao);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     */
    @WebMethod(operationName = "SetPedidoJSON")
    public void setPedidoJSON(
        @WebParam(name = "MbWayKey", partName = "MbWayKey")
        String mbWayKey,
        @WebParam(name = "canal", partName = "canal")
        String canal,
        @WebParam(name = "referencia", partName = "referencia")
        String referencia,
        @WebParam(name = "valor", partName = "valor")
        String valor,
        @WebParam(name = "nrtlm", partName = "nrtlm")
        String nrtlm,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "descricao", partName = "descricao")
        String descricao);

}
