
package ifthenpay.mbws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <font  size="4"><strong>WebService de Suporte ao Servi�o <br /><font color="#008C8C">IFMB - Pagamentos por Refer�ncia Multibanco</font>.</strong></font> <br /><br />
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "IfmbWS", targetNamespace = "https://www.ifthenpay.com/", wsdlLocation = "file:/C:/workspace/beta/org.dma.services.payment/wsdl/ifmbws.xml")
public class IfmbWS
    extends Service
{

    private final static URL IFMBWS_WSDL_LOCATION;
    private final static WebServiceException IFMBWS_EXCEPTION;
    private final static QName IFMBWS_QNAME = new QName("https://www.ifthenpay.com/", "IfmbWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = IfmbWS.class.getClassLoader().getResource("wsdl/ifmbws.xml");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        IFMBWS_WSDL_LOCATION = url;
        IFMBWS_EXCEPTION = e;
    }

    public IfmbWS() {
        super(__getWsdlLocation(), IFMBWS_QNAME);
    }

    public IfmbWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), IFMBWS_QNAME, features);
    }

    public IfmbWS(URL wsdlLocation) {
        super(wsdlLocation, IFMBWS_QNAME);
    }

    public IfmbWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IFMBWS_QNAME, features);
    }

    public IfmbWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IfmbWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IfmbWSSoap
     */
    @WebEndpoint(name = "IfmbWSSoap")
    public IfmbWSSoap getIfmbWSSoap() {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSSoap"), IfmbWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IfmbWSSoap
     */
    @WebEndpoint(name = "IfmbWSSoap")
    public IfmbWSSoap getIfmbWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSSoap"), IfmbWSSoap.class, features);
    }

    /**
     *
     * @return
     *     returns IfmbWSSoap
     */
    @WebEndpoint(name = "IfmbWSSoap12")
    public IfmbWSSoap getIfmbWSSoap12() {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSSoap12"), IfmbWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IfmbWSSoap
     */
    @WebEndpoint(name = "IfmbWSSoap12")
    public IfmbWSSoap getIfmbWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSSoap12"), IfmbWSSoap.class, features);
    }

    /**
     *
     * @return
     *     returns IfmbWSHttpGet
     */
    @WebEndpoint(name = "IfmbWSHttpGet")
    public IfmbWSHttpGet getIfmbWSHttpGet() {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSHttpGet"), IfmbWSHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IfmbWSHttpGet
     */
    @WebEndpoint(name = "IfmbWSHttpGet")
    public IfmbWSHttpGet getIfmbWSHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSHttpGet"), IfmbWSHttpGet.class, features);
    }

    /**
     *
     * @return
     *     returns IfmbWSHttpPost
     */
    @WebEndpoint(name = "IfmbWSHttpPost")
    public IfmbWSHttpPost getIfmbWSHttpPost() {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSHttpPost"), IfmbWSHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IfmbWSHttpPost
     */
    @WebEndpoint(name = "IfmbWSHttpPost")
    public IfmbWSHttpPost getIfmbWSHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.ifthenpay.com/", "IfmbWSHttpPost"), IfmbWSHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IFMBWS_EXCEPTION!= null) {
            throw IFMBWS_EXCEPTION;
        }
        return IFMBWS_WSDL_LOCATION;
    }

}
