
package ifthenpay.mbws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IfmbWSSoap", targetNamespace = "https://www.ifthenpay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IfmbWSSoap {


    /**
     * 
     * @param chavebackoffice
     * @param dtHrInicio
     * @param valor
     * @param dtHrFim
     * @param subentidade
     * @param entidade
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.ArrayOfIfmb
     */
    @WebMethod(action = "https://www.ifthenpay.com/getPayments")
    @WebResult(name = "getPaymentsResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getPayments", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPayments")
    @ResponseWrapper(localName = "getPaymentsResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsResponse")
    public ArrayOfIfmb getPayments(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice,
        @WebParam(name = "entidade", targetNamespace = "https://www.ifthenpay.com/")
        String entidade,
        @WebParam(name = "subentidade", targetNamespace = "https://www.ifthenpay.com/")
        String subentidade,
        @WebParam(name = "dtHrInicio", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrInicio,
        @WebParam(name = "dtHrFim", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrFim,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor);

    /**
     * 
     * @param chavebackoffice
     * @param dtHrInicio
     * @param valor
     * @param sandbox
     * @param dtHrFim
     * @param subentidade
     * @param entidade
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.ArrayOfIfmb
     */
    @WebMethod(action = "https://www.ifthenpay.com/getPaymentsWithSandBox")
    @WebResult(name = "getPaymentsWithSandBoxResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getPaymentsWithSandBox", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsWithSandBox")
    @ResponseWrapper(localName = "getPaymentsWithSandBoxResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsWithSandBoxResponse")
    public ArrayOfIfmb getPaymentsWithSandBox(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice,
        @WebParam(name = "entidade", targetNamespace = "https://www.ifthenpay.com/")
        String entidade,
        @WebParam(name = "subentidade", targetNamespace = "https://www.ifthenpay.com/")
        String subentidade,
        @WebParam(name = "dtHrInicio", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrInicio,
        @WebParam(name = "dtHrFim", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrFim,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor,
        @WebParam(name = "sandbox", targetNamespace = "https://www.ifthenpay.com/")
        int sandbox);

    /**
     * 
     * @param chavebackoffice
     * @param dtHrInicio
     * @param valor
     * @param dtHrFim
     * @param subentidade
     * @param entidade
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.ArrayOfIfmb
     */
    @WebMethod(action = "https://www.ifthenpay.com/getPaymentsXML")
    @WebResult(name = "getPaymentsXMLResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getPaymentsXML", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsXML")
    @ResponseWrapper(localName = "getPaymentsXMLResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsXMLResponse")
    public ArrayOfIfmb getPaymentsXML(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice,
        @WebParam(name = "entidade", targetNamespace = "https://www.ifthenpay.com/")
        String entidade,
        @WebParam(name = "subentidade", targetNamespace = "https://www.ifthenpay.com/")
        String subentidade,
        @WebParam(name = "dtHrInicio", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrInicio,
        @WebParam(name = "dtHrFim", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrFim,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor);

    /**
     * 
     * @param chavebackoffice
     * @param dtHrInicio
     * @param valor
     * @param dtHrFim
     * @param subentidade
     * @param entidade
     * @param referencia
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://www.ifthenpay.com/getPaymentsJSON")
    @WebResult(name = "getPaymentsJSONResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getPaymentsJSON", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsJSON")
    @ResponseWrapper(localName = "getPaymentsJSONResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetPaymentsJSONResponse")
    public String getPaymentsJSON(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice,
        @WebParam(name = "entidade", targetNamespace = "https://www.ifthenpay.com/")
        String entidade,
        @WebParam(name = "subentidade", targetNamespace = "https://www.ifthenpay.com/")
        String subentidade,
        @WebParam(name = "dtHrInicio", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrInicio,
        @WebParam(name = "dtHrFim", targetNamespace = "https://www.ifthenpay.com/")
        String dtHrFim,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor);

    /**
     * 
     * @param chavebackoffice
     * @return
     *     returns https.www_ifthenpay.ArrayOfIfmb
     */
    @WebMethod(action = "https://www.ifthenpay.com/getEntidadeSubentidade")
    @WebResult(name = "getEntidadeSubentidadeResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getEntidadeSubentidade", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidade")
    @ResponseWrapper(localName = "getEntidadeSubentidadeResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeResponse")
    public ArrayOfIfmb getEntidadeSubentidade(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice);

    /**
     * 
     * @param chavebackoffice
     * @return
     *     returns https.www_ifthenpay.ArrayOfIfmb
     */
    @WebMethod(action = "https://www.ifthenpay.com/getEntidadeSubentidadeXml")
    @WebResult(name = "getEntidadeSubentidadeXmlResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getEntidadeSubentidadeXml", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeXml")
    @ResponseWrapper(localName = "getEntidadeSubentidadeXmlResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeXmlResponse")
    public ArrayOfIfmb getEntidadeSubentidadeXml(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice);

    /**
     * 
     * @param chavebackoffice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://www.ifthenpay.com/getEntidadeSubentidadeJson")
    @WebResult(name = "getEntidadeSubentidadeJsonResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "getEntidadeSubentidadeJson", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeJson")
    @ResponseWrapper(localName = "getEntidadeSubentidadeJsonResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeJsonResponse")
    public String getEntidadeSubentidadeJson(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice);

    /**
     * 
     * @param chavebackoffice
     */
    @WebMethod(action = "https://www.ifthenpay.com/getEntidadeSubentidadeJsonV2")
    @RequestWrapper(localName = "getEntidadeSubentidadeJsonV2", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeJsonV2")
    @ResponseWrapper(localName = "getEntidadeSubentidadeJsonV2Response", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.GetEntidadeSubentidadeJsonV2Response")
    public void getEntidadeSubentidadeJsonV2(
        @WebParam(name = "chavebackoffice", targetNamespace = "https://www.ifthenpay.com/")
        String chavebackoffice);

}
