
package pt.at.webservices.factemipf.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "faturas", targetNamespace = "http://servicos.portaldasfinancas.gov.pt/faturas/", 
wsdlLocation = "http://info.portaldasfinancas.gov.pt/NR/rdonlyres/02357996-29FC-4F11-9F1D-6EA2B9210D60/0/factemiws.wsdl")
public class Faturas_Service extends Service {

    private final static URL FATURAS_WSDL_LOCATION=null;
    private final static QName FATURAS_QNAME = new QName("http://servicos.portaldasfinancas.gov.pt/faturas/", "faturas");

    public Faturas_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Faturas_Service() {
        super(FATURAS_WSDL_LOCATION, FATURAS_QNAME);
    }

    public Faturas_Service(URL wsdlLocation) {
        super(wsdlLocation, FATURAS_QNAME);
    }

    /**
     * 
     * @return
     *     returns Faturas
     */
    @WebEndpoint(name = "faturasSOAP")
    public Faturas getFaturasSOAP() {
        return super.getPort(new QName("http://servicos.portaldasfinancas.gov.pt/faturas/", "faturasSOAP"), Faturas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Faturas
     */
    @WebEndpoint(name = "faturasSOAP")
    public Faturas getFaturasSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.portaldasfinancas.gov.pt/faturas/", "faturasSOAP"), Faturas.class, features);
    }


}
