
package ifthenpay.mbw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IfthenPayMBWSoap", targetNamespace = "https://www.ifthenpay.com/")
@XmlSeeAlso({
    ifthenpay.mbw.ObjectFactory.class,
    ifthenpay.mbw.abstracttypes.ObjectFactory.class,
    org.xmlsoap.schemas.soap.encoding.ObjectFactory.class
})
public interface IfthenPayMBWSoap {


    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.RespostaPedido
     */
    @WebMethod(operationName = "SetPedidoSync", action = "https://www.ifthenpay.com/SetPedidoSync")
    @WebResult(name = "SetPedidoSyncResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "SetPedidoSync", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoSync")
    @ResponseWrapper(localName = "SetPedidoSyncResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoSyncResponse")
    public RespostaPedido setPedidoSync(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor,
        @WebParam(name = "nrtlm", targetNamespace = "https://www.ifthenpay.com/")
        String nrtlm,
        @WebParam(name = "email", targetNamespace = "https://www.ifthenpay.com/")
        String email,
        @WebParam(name = "descricao", targetNamespace = "https://www.ifthenpay.com/")
        String descricao);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     */
    @WebMethod(operationName = "SetPedidoSyncJSON", action = "https://www.ifthenpay.com/SetPedidoSyncJSON")
    @RequestWrapper(localName = "SetPedidoSyncJSON", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoSyncJSON")
    @ResponseWrapper(localName = "SetPedidoSyncJSONResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoSyncJSONResponse")
    public void setPedidoSyncJSON(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor,
        @WebParam(name = "nrtlm", targetNamespace = "https://www.ifthenpay.com/")
        String nrtlm,
        @WebParam(name = "email", targetNamespace = "https://www.ifthenpay.com/")
        String email,
        @WebParam(name = "descricao", targetNamespace = "https://www.ifthenpay.com/")
        String descricao);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     */
    @WebMethod(operationName = "EstadoPedidosSyncJSON", action = "https://www.ifthenpay.com/EstadoPedidosSyncJSON")
    @RequestWrapper(localName = "EstadoPedidosSyncJSON", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidosSyncJSON")
    @ResponseWrapper(localName = "EstadoPedidosSyncJSONResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidosSyncJSONResponse")
    public void estadoPedidosSyncJSON(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "idspagamento", targetNamespace = "https://www.ifthenpay.com/")
        ArrayOfString idspagamento);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     * @return
     *     returns https.www_ifthenpay.RespostaPedidoEstado
     */
    @WebMethod(operationName = "EstadoPedidos", action = "https://www.ifthenpay.com/EstadoPedidos")
    @WebResult(name = "EstadoPedidosResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "EstadoPedidos", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidos")
    @ResponseWrapper(localName = "EstadoPedidosResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidosResponse")
    public RespostaPedidoEstado estadoPedidos(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "idspagamento", targetNamespace = "https://www.ifthenpay.com/")
        ArrayOfString idspagamento);

    /**
     * 
     * @param mbWayKey
     * @param idspagamento
     * @param canal
     */
    @WebMethod(operationName = "EstadoPedidosJSON", action = "https://www.ifthenpay.com/EstadoPedidosJSON")
    @RequestWrapper(localName = "EstadoPedidosJSON", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidosJSON")
    @ResponseWrapper(localName = "EstadoPedidosJSONResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.EstadoPedidosJSONResponse")
    public void estadoPedidosJSON(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "idspagamento", targetNamespace = "https://www.ifthenpay.com/")
        ArrayOfString idspagamento);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     * @return
     *     returns https.www_ifthenpay.RespostaPedido
     */
    @WebMethod(operationName = "SetPedido", action = "https://www.ifthenpay.com/SetPedido")
    @WebResult(name = "SetPedidoResult", targetNamespace = "https://www.ifthenpay.com/")
    @RequestWrapper(localName = "SetPedido", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedido")
    @ResponseWrapper(localName = "SetPedidoResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoResponse")
    public RespostaPedido setPedido(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor,
        @WebParam(name = "nrtlm", targetNamespace = "https://www.ifthenpay.com/")
        String nrtlm,
        @WebParam(name = "email", targetNamespace = "https://www.ifthenpay.com/")
        String email,
        @WebParam(name = "descricao", targetNamespace = "https://www.ifthenpay.com/")
        String descricao);

    /**
     * 
     * @param nrtlm
     * @param mbWayKey
     * @param email
     * @param valor
     * @param descricao
     * @param canal
     * @param referencia
     */
    @WebMethod(operationName = "SetPedidoJSON", action = "https://www.ifthenpay.com/SetPedidoJSON")
    @RequestWrapper(localName = "SetPedidoJSON", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoJSON")
    @ResponseWrapper(localName = "SetPedidoJSONResponse", targetNamespace = "https://www.ifthenpay.com/", className = "https.www_ifthenpay.SetPedidoJSONResponse")
    public void setPedidoJSON(
        @WebParam(name = "MbWayKey", targetNamespace = "https://www.ifthenpay.com/")
        String mbWayKey,
        @WebParam(name = "canal", targetNamespace = "https://www.ifthenpay.com/")
        String canal,
        @WebParam(name = "referencia", targetNamespace = "https://www.ifthenpay.com/")
        String referencia,
        @WebParam(name = "valor", targetNamespace = "https://www.ifthenpay.com/")
        String valor,
        @WebParam(name = "nrtlm", targetNamespace = "https://www.ifthenpay.com/")
        String nrtlm,
        @WebParam(name = "email", targetNamespace = "https://www.ifthenpay.com/")
        String email,
        @WebParam(name = "descricao", targetNamespace = "https://www.ifthenpay.com/")
        String descricao);

}
