
package pt.gov.portaldasfinancas.servicos.documentos;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "fatcorewsPortService", targetNamespace = "http://factemi.at.min_financas.pt/documents", wsdlLocation = "file:wsdl/Fatcorews.wsdl")
public class FatcorewsPortService
    extends Service
{

    private final static URL FATCOREWSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FATCOREWSPORTSERVICE_EXCEPTION;
    private final static QName FATCOREWSPORTSERVICE_QNAME = new QName("http://factemi.at.min_financas.pt/documents", "fatcorewsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = FatcorewsPortService.class.getClassLoader().getResource("wsdl/Fatcorews.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        FATCOREWSPORTSERVICE_WSDL_LOCATION = url;
        FATCOREWSPORTSERVICE_EXCEPTION = e;
    }

    public FatcorewsPortService() {
        super(__getWsdlLocation(), FATCOREWSPORTSERVICE_QNAME);
    }

    public FatcorewsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FATCOREWSPORTSERVICE_QNAME, features);
    }

    public FatcorewsPortService(URL wsdlLocation) {
        super(wsdlLocation, FATCOREWSPORTSERVICE_QNAME);
    }

    public FatcorewsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FATCOREWSPORTSERVICE_QNAME, features);
    }

    public FatcorewsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FatcorewsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FatcorewsPort
     */
    @WebEndpoint(name = "fatcorewsPortSoap11")
    public FatcorewsPort getFatcorewsPortSoap11() {
        return super.getPort(new QName("http://factemi.at.min_financas.pt/documents", "fatcorewsPortSoap11"), FatcorewsPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FatcorewsPort
     */
    @WebEndpoint(name = "fatcorewsPortSoap11")
    public FatcorewsPort getFatcorewsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://factemi.at.min_financas.pt/documents", "fatcorewsPortSoap11"), FatcorewsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FATCOREWSPORTSERVICE_EXCEPTION!= null) {
            throw FATCOREWSPORTSERVICE_EXCEPTION;
        }
        return FATCOREWSPORTSERVICE_WSDL_LOCATION;
    }

}
