javacDefaultEncoding.. = UTF-8
source.. = src/
output.. = bin/
bin.includes = .,\
               src/,\
               META-INF/,\
               libraries/lib/commons-codec-1.10.jar,\
               libraries/lib/commons-collections4-4.1.jar,\
               libraries/lib/commons-logging-1.2.jar,\
               libraries/lib/junit-4.12.jar,\
               libraries/lib/log4j-1.2.17.jar,\
               libraries/ooxml-lib/curvesapi-1.04.jar,\
               libraries/ooxml-lib/xmlbeans-2.6.0.jar,\
               libraries/poi-3.17.jar,\
               libraries/poi-examples-3.17.jar,\
               libraries/poi-excelant-3.17.jar,\
               libraries/poi-ooxml-3.17.jar,\
               libraries/poi-ooxml-schemas-3.17.jar,\
               libraries/poi-scratchpad-3.17.jar
