
package pt.gov.portaldasfinancas.servicos.etaxfree.taxfreeservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "TaxFreeServiceImplService", targetNamespace = "http://servicos.portaldasfinancas.gov.pt/eTaxFree/TaxFreeService", wsdlLocation = "file:/C:/workspace/dev/org.dma.services.at/eTaxFreeSoapWebServices.wsdl")
public class TaxFreeServiceImplService
    extends Service
{

    private final static URL TAXFREESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TAXFREESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TAXFREESERVICEIMPLSERVICE_QNAME = new QName("http://servicos.portaldasfinancas.gov.pt/eTaxFree/TaxFreeService", "TaxFreeServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:eTaxFreeSoapWebServices.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAXFREESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TAXFREESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TaxFreeServiceImplService() {
        super(__getWsdlLocation(), TAXFREESERVICEIMPLSERVICE_QNAME);
    }

    public TaxFreeServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXFREESERVICEIMPLSERVICE_QNAME, features);
    }

    public TaxFreeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TAXFREESERVICEIMPLSERVICE_QNAME);
    }

    public TaxFreeServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXFREESERVICEIMPLSERVICE_QNAME, features);
    }

    public TaxFreeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxFreeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TaxFreeService
     */
    @WebEndpoint(name = "TaxFreeServicePort")
    public TaxFreeService getTaxFreeServicePort() {
        return super.getPort(new QName("http://servicos.portaldasfinancas.gov.pt/eTaxFree/TaxFreeService", "TaxFreeServicePort"), TaxFreeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxFreeService
     */
    @WebEndpoint(name = "TaxFreeServicePort")
    public TaxFreeService getTaxFreeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.portaldasfinancas.gov.pt/eTaxFree/TaxFreeService", "TaxFreeServicePort"), TaxFreeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXFREESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TAXFREESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TAXFREESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
