
package pt.gov.portaldasfinancas.servicos.series;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SeriesWSService", targetNamespace = "http://at.gov.pt/", wsdlLocation = "file:wsdl/Series.wsdl")
public class SeriesWSService
    extends Service
{

    private final static URL SERIESWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERIESWSSERVICE_EXCEPTION;
    private final static QName SERIESWSSERVICE_QNAME = new QName("http://at.gov.pt/", "SeriesWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = SeriesWSService.class.getClassLoader().getResource("wsdl/Series.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        SERIESWSSERVICE_WSDL_LOCATION = url;
        SERIESWSSERVICE_EXCEPTION = e;
    }

    public SeriesWSService() {
        super(__getWsdlLocation(), SERIESWSSERVICE_QNAME);
    }

    public SeriesWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERIESWSSERVICE_QNAME, features);
    }

    public SeriesWSService(URL wsdlLocation) {
        super(wsdlLocation, SERIESWSSERVICE_QNAME);
    }

    public SeriesWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERIESWSSERVICE_QNAME, features);
    }

    public SeriesWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeriesWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SeriesWS
     */
    @WebEndpoint(name = "SeriesWSPort")
    public SeriesWS getSeriesWSPort() {
        return super.getPort(new QName("http://at.gov.pt/", "SeriesWSPort"), SeriesWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeriesWS
     */
    @WebEndpoint(name = "SeriesWSPort")
    public SeriesWS getSeriesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://at.gov.pt/", "SeriesWSPort"), SeriesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERIESWSSERVICE_EXCEPTION!= null) {
            throw SERIESWSSERVICE_EXCEPTION;
        }
        return SERIESWSSERVICE_WSDL_LOCATION;
    }

}
