
package pt.at.webservices.sgdt.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "documentosTransporte", targetNamespace = "https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", 
wsdlLocation = "http://info.portaldasfinancas.gov.pt/NR/rdonlyres/A75E1110-7EB8-479E-BC09-6D5B726F6A1C/0/documentosTransporte.wsdl")
public class DocumentosTransporte_Service extends Service {

    private final static URL DOCUMENTOSTRANSPORTE_WSDL_LOCATION=null;
    private final static QName DOCUMENTOSTRANSPORTE_QNAME = new QName("https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", "documentosTransporte");

    public DocumentosTransporte_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentosTransporte_Service() {
        super(DOCUMENTOSTRANSPORTE_WSDL_LOCATION, DOCUMENTOSTRANSPORTE_QNAME);
    }

    /**
     * 
     * @return
     *     returns DocumentosTransporte
     */
    @WebEndpoint(name = "documentosTransporteSOAP")
    public DocumentosTransporte getDocumentosTransporteSOAP() {
        return super.getPort(new QName("https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", "documentosTransporteSOAP"), DocumentosTransporte.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentosTransporte
     */
    @WebEndpoint(name = "documentosTransporteSOAP")
    public DocumentosTransporte getDocumentosTransporteSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", "documentosTransporteSOAP"), DocumentosTransporte.class, features);
    }

}
