javacDefaultEncoding.. = UTF-8
source.. = src/
output.. = bin/
bin.includes = .,\
               src/,\
               META-INF/,\
               src/wsdl/CTMessageService.wsdl,\
               src/wsdl/InvoiceManager-1.2.0.wsdl,\
               src/wsdl/NetixMessaging-1.2.0.wsdl,\
               CIUS/Fatura CIUS-PT_UBL2.1_V1.0.0.xml,\
               CIUS/Nota de Credito CIUS-PT_UBL2.1_V1.0.0.xml

