
package com.generixgroup.pt.messaging.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Webservice", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Webservice {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "version", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.VersionResponse")
    @Action(input = "http://webservice.messaging.pt.generixgroup.com/Webservice/versionRequest", output = "http://webservice.messaging.pt.generixgroup.com/Webservice/versionResponse")
    public String version();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.generixgroup.pt.messaging.webservice.GetDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.GetDocument")
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.GetDocumentResponse")
    @Action(input = "http://webservice.messaging.pt.generixgroup.com/Webservice/getDocumentRequest", output = "http://webservice.messaging.pt.generixgroup.com/Webservice/getDocumentResponse")
    public GetDocResponse getDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        Credentials arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.generixgroup.pt.messaging.webservice.ListDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDocuments", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.ListDocuments")
    @ResponseWrapper(localName = "listDocumentsResponse", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.ListDocumentsResponse")
    @Action(input = "http://webservice.messaging.pt.generixgroup.com/Webservice/listDocumentsRequest", output = "http://webservice.messaging.pt.generixgroup.com/Webservice/listDocumentsResponse")
    public ListDocResponse listDocuments(
        @WebParam(name = "arg0", targetNamespace = "")
        Credentials arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.generixgroup.pt.messaging.webservice.UploadDocResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadDocument", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.UploadDocument")
    @ResponseWrapper(localName = "uploadDocumentResponse", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.UploadDocumentResponse")
    @Action(input = "http://webservice.messaging.pt.generixgroup.com/Webservice/uploadDocumentRequest", output = "http://webservice.messaging.pt.generixgroup.com/Webservice/uploadDocumentResponse")
    public UploadDocResponse uploadDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Credentials arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        RoutingInfo arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.generixgroup.pt.messaging.webservice.GetDocResponse
     * @throws MalformedURLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.DeleteDocument")
    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "http://webservice.messaging.pt.generixgroup.com/", className = "com.generixgroup.pt.messaging.webservice.DeleteDocumentResponse")
    @Action(input = "http://webservice.messaging.pt.generixgroup.com/Webservice/deleteDocumentRequest", output = "http://webservice.messaging.pt.generixgroup.com/Webservice/deleteDocumentResponse", fault = {
        @FaultAction(className = MalformedURLException_Exception.class, value = "http://webservice.messaging.pt.generixgroup.com/Webservice/deleteDocument/Fault/MalformedURLException")
    })
    public GetDocResponse deleteDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        Credentials arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws MalformedURLException_Exception
    ;

}
